# Generated by Django 2.2.9 on 2020-04-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triphistorymodel',
            name='rider_id',
            field=models.IntegerField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
